name: Are The Types Wrong checker
description: Action that runs and validates npm packages with Are The Types Wrong (attw)
author: boyum

branding:
  icon: package
  color: yellow

inputs:
  working-directory:
    required: false
    description: The working directory to run the command in
    default: "."

runs:
  using: composite

  steps:
    - name: Clone the repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 20

    - name: Check if the Types Are Wrong
      shell: bash
      run: npx -p @arethetypeswrong/cli attw --pack ${{ inputs.working-directory }}
